---
- name: Converge
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    metamod_source_install_path: /home/steam/dod-source/dod
    dod_source_ip: 127.0.0.1
    dod_source_mapcycle:
      - dod_flash
    dod_source_server_cfg: |
      hostname "SourceHut test Day of Defeat Server"
      rcon_password srht
      mp_friendlyfire 1
      mp_autoteambalance 1
  tasks:
    - name: "Include aversiste.steamcmd"
      include_role:
        name: "aversiste.steamcmd"
    - name: "Include ansible-role-dod-source"
      include_role:
        name: "ansible-role-dod-source"
